"""
TestGenerator — generates conformance test suites from synthesised SpecBundles.

Design:
- API_ENDPOINT specs → pytest + httpx API conformance tests
- USER_FLOW specs    → pytest + playwright E2E tests
- AUTH specs         → pytest + httpx auth scenario tests
- DATA_MODEL specs   → pytest + httpx schema validation tests
- All tests are dual-execution: same file runs against TARGET_URL or CLONE_URL
  via a BASE_URL pytest fixture that reads from env.
- Tolerated variance: IDs, timestamps, and ordering excluded from assertions.
- Output: test files written to output_dir/tests/conformance/

Invariants:
    INV-TG-001: Every generated test file is valid Python (ast.parse passes).
    INV-TG-002: At least one test is generated per SpecItem that has an
                api_contracts or user_flows or auth_scenarios entry.
    INV-TG-003: spec_coverage[feature] == True iff >=1 test generated for that feature.
"""

from __future__ import annotations

import ast
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from scripts.models import SpecBundle, SpecItem
from scripts.spec_store import SpecStore

# ---------------------------------------------------------------------------
# Non-deterministic field names — excluded from conformance assertions
# ---------------------------------------------------------------------------

_VOLATILE_FIELDS = frozenset(
    [
        "id",
        "uuid",
        "created_at",
        "updated_at",
        "modified_at",
        "timestamp",
        "token",
        "session_id",
        "request_id",
        "trace_id",
        "etag",
        "last_modified",
    ]
)

# ---------------------------------------------------------------------------
# Output types
# ---------------------------------------------------------------------------


@dataclass
class GeneratedTestSuite:
    output_dir: Path
    test_files: list[Path]
    total_tests: int
    by_category: dict[str, int]  # api: N, e2e: N, auth: N, schema: N
    spec_coverage: dict[str, bool]  # feature -> has_tests


# ---------------------------------------------------------------------------
# Code generation helpers
# ---------------------------------------------------------------------------

_DUAL_EXEC_FIXTURE = '''\
import os
import pytest


@pytest.fixture(scope="session")
def base_url() -> str:
    """
    Dual-execution fixture.
    Run with BASE_URL=<target> for target conformance,
    or BASE_URL=<clone> for clone conformance.
    """
    url = os.environ.get("BASE_URL", os.environ.get("TARGET_URL", "http://localhost:8000"))
    return url.rstrip("/")


def assert_equivalent(
    target: dict,
    clone: dict,
    *,
    ignore: list[str] | None = None,
    path: str = "",
) -> None:
    """
    Assert two response dicts are semantically equivalent.

    Tolerates variance in non-deterministic fields (IDs, timestamps, etc.)
    by removing them before comparison.

    Args:
        target: Response dict from the target application.
        clone:  Response dict from the clone application.
        ignore: Additional field names to exclude from comparison.
        path:   Dot-notation path for error messages (internal use).
    """
    _ignore = set(_VOLATILE_FIELDS) | set(ignore or [])

    def _strip(obj: Any, _ignore: set) -> Any:
        if isinstance(obj, dict):
            return {k: _strip(v, _ignore) for k, v in obj.items() if k not in _ignore}
        if isinstance(obj, list):
            return [_strip(item, _ignore) for item in obj]
        return obj

    stripped_target = _strip(target, _ignore)
    stripped_clone = _strip(clone, _ignore)
    assert stripped_target == stripped_clone, (
        f"Response mismatch at {path!r}:\\n"
        f"  target: {stripped_target}\\n"
        f"  clone:  {stripped_clone}"
    )


_VOLATILE_FIELDS = frozenset([
    "id", "uuid", "created_at", "updated_at", "modified_at",
    "timestamp", "token", "session_id", "request_id", "trace_id",
    "etag", "last_modified",
])
'''

_API_TEST_TEMPLATE = '''\
"""
API conformance tests for feature: {feature}
Generated by duplicat-rex TestGenerator.

Run against target:
    BASE_URL=https://target.example.com pytest {filename}
Run against clone:
    BASE_URL=https://clone.example.com pytest {filename}
"""

from __future__ import annotations

import os
import pytest
import httpx

# ---------------------------------------------------------------------------
# Dual-execution fixture
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def base_url() -> str:
    url = os.environ.get("BASE_URL", os.environ.get("TARGET_URL", "http://localhost:8000"))
    return url.rstrip("/")


# ---------------------------------------------------------------------------
# Tolerated variance
# ---------------------------------------------------------------------------

_VOLATILE_FIELDS = frozenset([
    "id", "uuid", "created_at", "updated_at", "modified_at",
    "timestamp", "token", "session_id", "request_id", "trace_id",
    "etag", "last_modified",
])


def assert_equivalent(target: dict, clone: dict, *, ignore: list[str] | None = None) -> None:
    _ignore = set(_VOLATILE_FIELDS) | set(ignore or [])

    def _strip(obj):
        if isinstance(obj, dict):
            return {{k: _strip(v) for k, v in obj.items() if k not in _ignore}}
        if isinstance(obj, list):
            return [_strip(i) for i in obj]
        return obj

    assert _strip(target) == _strip(clone), (
        f"Response mismatch:\\n  target: {{_strip(target)}}\\n  clone: {{_strip(clone)}}"
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

{test_cases}
'''

_E2E_TEST_TEMPLATE = '''\
"""
E2E conformance tests for feature: {feature}
Generated by duplicat-rex TestGenerator.

Run against target:
    BASE_URL=https://target.example.com pytest {filename}
Run against clone:
    BASE_URL=https://clone.example.com pytest {filename}
"""

from __future__ import annotations

import os
import pytest
from playwright.sync_api import Page, expect


@pytest.fixture(scope="session")
def base_url() -> str:
    url = os.environ.get("BASE_URL", os.environ.get("TARGET_URL", "http://localhost:8000"))
    return url.rstrip("/")


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

{test_cases}
'''

_AUTH_TEST_TEMPLATE = '''\
"""
Auth conformance tests for feature: {feature}
Generated by duplicat-rex TestGenerator.

Run against target:
    BASE_URL=https://target.example.com pytest {filename}
Run against clone:
    BASE_URL=https://clone.example.com pytest {filename}
"""

from __future__ import annotations

import os
import pytest
import httpx


@pytest.fixture(scope="session")
def base_url() -> str:
    url = os.environ.get("BASE_URL", os.environ.get("TARGET_URL", "http://localhost:8000"))
    return url.rstrip("/")


_VOLATILE_FIELDS = frozenset([
    "id", "uuid", "created_at", "updated_at", "modified_at",
    "timestamp", "token", "session_id", "request_id", "trace_id",
    "etag", "last_modified",
])


def assert_equivalent(target: dict, clone: dict, *, ignore: list[str] | None = None) -> None:
    _ignore = set(_VOLATILE_FIELDS) | set(ignore or [])

    def _strip(obj):
        if isinstance(obj, dict):
            return {{k: _strip(v) for k, v in obj.items() if k not in _ignore}}
        if isinstance(obj, list):
            return [_strip(i) for i in obj]
        return obj

    assert _strip(target) == _strip(clone), (
        f"Response mismatch:\\n  target: {{_strip(target)}}\\n  clone: {{_strip(clone)}}"
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

{test_cases}
'''

_SCHEMA_TEST_TEMPLATE = '''\
"""
Schema validation tests for feature: {feature}
Generated by duplicat-rex TestGenerator.

Run against target:
    BASE_URL=https://target.example.com pytest {filename}
Run against clone:
    BASE_URL=https://clone.example.com pytest {filename}
"""

from __future__ import annotations

import os
import pytest
import httpx


@pytest.fixture(scope="session")
def base_url() -> str:
    url = os.environ.get("BASE_URL", os.environ.get("TARGET_URL", "http://localhost:8000"))
    return url.rstrip("/")


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

{test_cases}
'''


# ---------------------------------------------------------------------------
# TestGenerator
# ---------------------------------------------------------------------------


class TestGenerator:
    """
    Generates conformance test suites from synthesised SpecBundles.

    Each SpecItem in the bundle is mapped to one or more generated test files:
    - api_contracts  → tests/conformance/test_api_{feature}.py
    - user_flows     → tests/conformance/test_e2e_{feature}.py
    - auth_scenarios → tests/conformance/test_auth_{feature}.py
    - data_models    → tests/conformance/test_schema_{feature}.py

    All generated tests are dual-execution: set BASE_URL env var to switch
    between target and clone conformance runs.
    """

    def __init__(self, spec_store: SpecStore) -> None:
        self.spec_store = spec_store

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(
        self,
        bundle: SpecBundle,
        *,
        output_dir: Path,
        target_url: str,
        clone_url: str,
    ) -> GeneratedTestSuite:
        """
        Generate a full conformance test suite from a SpecBundle.

        For each SpecItem in the bundle, generate test cases:
        - API_ENDPOINT / api_contracts  → httpx-based API conformance tests
        - USER_FLOW / user_flows        → Playwright E2E test scripts
        - AUTH / auth_scenarios         → auth scenario tests
        - DATA_MODEL / data_models      → schema validation tests

        All tests are dual-execution: same test runs against both target_url
        and clone_url via BASE_URL env var.

        Tolerated variance: IDs, timestamps, ordering excluded from assertions.

        REQUIRES: bundle has at least one SpecItem.
        ENSURES:  returned suite.test_files are all valid Python (ast.parse).
        ENSURES:  spec_coverage[feature] == True iff >=1 test generated.
        """
        conformance_dir = output_dir / "tests" / "conformance"
        conformance_dir.mkdir(parents=True, exist_ok=True)

        test_files: list[Path] = []
        by_category: dict[str, int] = {"api": 0, "e2e": 0, "auth": 0, "schema": 0}
        spec_coverage: dict[str, bool] = {feature: False for feature in bundle.scope}

        for item in bundle.spec_items:
            feature = item.feature
            content = item.content

            # API conformance tests
            api_count = self._generate_api_tests(
                item, content, conformance_dir, test_files
            )
            by_category["api"] += api_count
            if api_count:
                spec_coverage[feature] = True

            # E2E tests
            e2e_count = self._generate_e2e_tests(
                item, content, conformance_dir, test_files
            )
            by_category["e2e"] += e2e_count
            if e2e_count:
                spec_coverage[feature] = True

            # Auth tests
            auth_count = self._generate_auth_tests(
                item, content, conformance_dir, test_files
            )
            by_category["auth"] += auth_count
            if auth_count:
                spec_coverage[feature] = True

            # Schema validation tests
            schema_count = self._generate_schema_tests(
                item, content, conformance_dir, test_files
            )
            by_category["schema"] += schema_count
            if schema_count:
                spec_coverage[feature] = True

        # Validate generated files are syntactically valid Python (INV-TG-001)
        for path in test_files:
            _validate_python_syntax(path)

        total_tests = sum(by_category.values())

        return GeneratedTestSuite(
            output_dir=output_dir,
            test_files=test_files,
            total_tests=total_tests,
            by_category=by_category,
            spec_coverage=spec_coverage,
        )

    # ------------------------------------------------------------------
    # Internal: API test generation
    # ------------------------------------------------------------------

    def _generate_api_tests(
        self,
        item: SpecItem,
        content: dict[str, Any],
        out_dir: Path,
        test_files: list[Path],
    ) -> int:
        """Generate API conformance tests from api_contracts in the spec content."""
        contracts = content.get("api_contracts", [])
        if not contracts:
            return 0

        feature = item.feature
        slug = _feature_slug(feature)
        filename = f"test_api_{slug}.py"
        test_cases_code = []

        for i, contract in enumerate(contracts):
            test_cases_code.append(_render_api_test_case(i, contract, feature))

        test_code = _API_TEST_TEMPLATE.format(
            feature=feature,
            filename=filename,
            test_cases="\n\n".join(test_cases_code),
        )

        out_path = out_dir / filename
        out_path.write_text(test_code, encoding="utf-8")
        test_files.append(out_path)
        return len(contracts)

    # ------------------------------------------------------------------
    # Internal: E2E test generation
    # ------------------------------------------------------------------

    def _generate_e2e_tests(
        self,
        item: SpecItem,
        content: dict[str, Any],
        out_dir: Path,
        test_files: list[Path],
    ) -> int:
        """Generate Playwright E2E tests from user_flows in the spec content."""
        flows = content.get("user_flows", [])
        # Also generate from ui_patterns if user_flows is absent
        if not flows:
            flows = content.get("ui_patterns", [])
        if not flows:
            return 0

        feature = item.feature
        slug = _feature_slug(feature)
        filename = f"test_e2e_{slug}.py"
        test_cases_code = []

        for i, flow in enumerate(flows):
            test_cases_code.append(_render_e2e_test_case(i, flow, feature))

        test_code = _E2E_TEST_TEMPLATE.format(
            feature=feature,
            filename=filename,
            test_cases="\n\n".join(test_cases_code),
        )

        out_path = out_dir / filename
        out_path.write_text(test_code, encoding="utf-8")
        test_files.append(out_path)
        return len(flows)

    # ------------------------------------------------------------------
    # Internal: Auth test generation
    # ------------------------------------------------------------------

    def _generate_auth_tests(
        self,
        item: SpecItem,
        content: dict[str, Any],
        out_dir: Path,
        test_files: list[Path],
    ) -> int:
        """Generate auth scenario tests from auth_scenarios in the spec content."""
        scenarios = content.get("auth_scenarios", [])
        # Also check business_rules for auth-related rules
        if not scenarios and item.spec_type in ("auth_spec", "auth_contract"):
            scenarios = [{"scenario": r} for r in content.get("business_rules", [])]
        if not scenarios:
            return 0

        feature = item.feature
        slug = _feature_slug(feature)
        filename = f"test_auth_{slug}.py"
        test_cases_code = []

        for i, scenario in enumerate(scenarios):
            test_cases_code.append(_render_auth_test_case(i, scenario, feature))

        test_code = _AUTH_TEST_TEMPLATE.format(
            feature=feature,
            filename=filename,
            test_cases="\n\n".join(test_cases_code),
        )

        out_path = out_dir / filename
        out_path.write_text(test_code, encoding="utf-8")
        test_files.append(out_path)
        return len(scenarios)

    # ------------------------------------------------------------------
    # Internal: Schema test generation
    # ------------------------------------------------------------------

    def _generate_schema_tests(
        self,
        item: SpecItem,
        content: dict[str, Any],
        out_dir: Path,
        test_files: list[Path],
    ) -> int:
        """Generate schema validation tests from data_models in the spec content."""
        models = content.get("data_models", [])
        if not models:
            return 0

        feature = item.feature
        slug = _feature_slug(feature)
        filename = f"test_schema_{slug}.py"
        test_cases_code = []

        for i, model in enumerate(models):
            test_cases_code.append(_render_schema_test_case(i, model, feature))

        test_code = _SCHEMA_TEST_TEMPLATE.format(
            feature=feature,
            filename=filename,
            test_cases="\n\n".join(test_cases_code),
        )

        out_path = out_dir / filename
        out_path.write_text(test_code, encoding="utf-8")
        test_files.append(out_path)
        return len(models)


# ---------------------------------------------------------------------------
# Code generation: individual test case renderers
# ---------------------------------------------------------------------------


def _render_api_test_case(idx: int, contract: dict[str, Any], feature: str) -> str:
    """Render a single API conformance test case."""
    endpoint = contract.get("endpoint", f"GET /api/{feature}")
    requires = contract.get("requires", [])
    ensures = contract.get("ensures", [])
    method, _, path = endpoint.partition(" ")
    method = method.upper() if method else "GET"
    path = path.strip() if path else f"/api/{feature}"

    # Build readable description
    desc_parts = []
    if requires:
        desc_parts.append(f"Requires: {'; '.join(str(r) for r in requires[:2])}")
    if ensures:
        desc_parts.append(f"Ensures: {'; '.join(str(e) for e in ensures[:2])}")
    description = " | ".join(desc_parts) or f"Conformance test for {endpoint}"

    fn_name = f"test_api_{feature.replace('-', '_').replace(' ', '_')}_{idx}"

    return textwrap.dedent(f"""\
        def {fn_name}(base_url: str) -> None:
            \"\"\"
            {description}
            Spec: {endpoint}
            \"\"\"
            url = f"{{base_url}}{path}"
            response = httpx.{method.lower()}(url, timeout=10.0)
            # Verify the endpoint is reachable and returns a valid response
            assert response.status_code < 500, (
                f"Server error {{response.status_code}} from {{url}}: {{response.text[:200]}}"
            )
        """)


def _render_e2e_test_case(idx: int, flow: dict[str, Any], feature: str) -> str:
    """Render a single E2E Playwright test case."""
    component = flow.get("component", flow.get("name", f"{feature} component"))
    behavior = flow.get("behavior", flow.get("description", flow.get("claim", "User interaction")))
    # Sanitize: remove newlines and excessive whitespace that break docstring indentation
    component = " ".join(str(component).split())[:200]
    behavior = " ".join(str(behavior).split())[:200]
    steps = flow.get("steps", flow.get("states", []))

    fn_name = f"test_e2e_{feature.replace('-', '_').replace(' ', '_')}_{idx}"
    steps_comment = (
        "\n    #   ".join(str(s) for s in steps[:5]) if steps else "navigate and interact"
    )

    return textwrap.dedent(f"""\
        def {fn_name}(page: Page, base_url: str) -> None:
            \"\"\"
            E2E test: {component}
            Behavior: {behavior}
            \"\"\"
            page.goto(base_url)
            # Steps: {steps_comment}
            # Verify the page loads without critical errors
            expect(page.locator("body")).to_be_visible()
        """)


def _render_auth_test_case(idx: int, scenario: dict[str, Any], feature: str) -> str:
    """Render a single auth scenario test case."""
    scenario_name = scenario.get("scenario", scenario.get("name", f"auth scenario {idx}"))
    method = scenario.get("method", "GET")
    path = scenario.get("path", f"/api/{feature}")
    expected_status = scenario.get("expected_status", scenario.get("unauthenticated_status", 401))

    fn_name = f"test_auth_{feature.replace('-', '_').replace(' ', '_')}_{idx}"

    return textwrap.dedent(f"""\
        def {fn_name}(base_url: str) -> None:
            \"\"\"
            Auth scenario: {scenario_name}
            Verify unauthenticated access is rejected.
            \"\"\"
            url = f"{{base_url}}{path}"
            response = httpx.{method.lower()}(url, timeout=10.0)
            assert response.status_code in ({expected_status}, 401, 403), (
                f"Expected auth rejection from {{url}}, got {{response.status_code}}"
            )
        """)


def _render_schema_test_case(idx: int, model: dict[str, Any], feature: str) -> str:
    """Render a single schema validation test case."""
    entity = model.get("entity", model.get("name", f"{feature} entity"))
    fields = model.get("fields", {})
    constraints = model.get("constraints", [])

    fn_name = f"test_schema_{feature.replace('-', '_').replace(' ', '_')}_{idx}"

    # Build field presence assertions
    field_assertions = ""
    if isinstance(fields, dict) and fields:
        field_list = list(fields.keys())[:5]
        field_assertions = "\n    ".join(
            f'assert {repr(k)} in data or {repr(k)} in data.get("data", {{}}), '
            f'"Missing field {k!r} from {entity}"'
            for k in field_list
        )
    elif isinstance(fields, list) and fields:
        field_assertions = "\n    ".join(
            f'assert {repr(k)} in data or {repr(k)} in data.get("data", {{}}), '
            f'"Missing field {k!r} from {entity}"'
            for k in fields[:5]
        )

    constraint_comment = (
        "\n    # Constraints: " + "; ".join(str(c) for c in constraints[:3])
        if constraints
        else ""
    )

    return textwrap.dedent(f"""\
        def {fn_name}(base_url: str) -> None:
            \"\"\"
            Schema validation: {entity}
            Fields: {list(fields.keys())[:5] if isinstance(fields, dict) else fields[:5]}
            \"\"\"
            url = f"{{base_url}}/api/{feature}"
            response = httpx.get(url, timeout=10.0)
            if response.status_code == 200:
                data = response.json()
                if isinstance(data, list) and data:
                    data = data[0]
                elif isinstance(data, dict) and "results" in data and data["results"]:
                    data = data["results"][0]{constraint_comment}
                {field_assertions if field_assertions else "pass  # schema check: valid JSON"}
        """)


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------


def _feature_slug(feature: str) -> str:
    """Convert a feature key to a safe Python identifier for file/function names."""
    return feature.lower().replace("-", "_").replace(" ", "_").replace(".", "_")


def _validate_python_syntax(path: Path) -> None:
    """Raise SyntaxError if the file is not valid Python (INV-TG-001)."""
    source = path.read_text(encoding="utf-8")
    try:
        ast.parse(source)
    except SyntaxError as exc:
        raise SyntaxError(
            f"Generated file {path} has invalid Python syntax: {exc}"
        ) from exc
